// letter_pool.dart

final List<Map<String, dynamic>> letterPool = [
  {'letter': 'A', 'count': 12, 'point': 1},
  {'letter': 'B', 'count': 2, 'point': 3},
  {'letter': 'C', 'count': 2, 'point': 4},
  {'letter': 'Ç', 'count': 2, 'point': 4},
  {'letter': 'D', 'count': 2, 'point': 3},
  {'letter': 'E', 'count': 8, 'point': 1},
  {'letter': 'F', 'count': 1, 'point': 7},
  {'letter': 'G', 'count': 1, 'point': 5},
  {'letter': 'Ğ', 'count': 1, 'point': 8},
  {'letter': 'H', 'count': 1, 'point': 5},
  {'letter': 'I', 'count': 4, 'point': 2},
  {'letter': 'İ', 'count': 7, 'point': 1},
  {'letter': 'J', 'count': 1, 'point': 10},
  {'letter': 'K', 'count': 7, 'point': 1},
  {'letter': 'L', 'count': 7, 'point': 1},
  {'letter': 'M', 'count': 4, 'point': 2},
  {'letter': 'N', 'count': 5, 'point': 1},
  {'letter': 'O', 'count': 3, 'point': 2},
  {'letter': 'Ö', 'count': 1, 'point': 7},
  {'letter': 'P', 'count': 1, 'point': 5},
  {'letter': 'R', 'count': 6, 'point': 1},
  {'letter': 'S', 'count': 3, 'point': 2},
  {'letter': 'Ş', 'count': 2, 'point': 4},
  {'letter': 'T', 'count': 5, 'point': 1},
  {'letter': 'U', 'count': 3, 'point': 2},
  {'letter': 'Ü', 'count': 2, 'point': 3},
  {'letter': 'V', 'count': 1, 'point': 7},
  {'letter': 'Y', 'count': 2, 'point': 3},
  {'letter': 'Z', 'count': 2, 'point': 4},
  {'letter': 'JOKER', 'count': 2, 'point': 0},
];
